# Generated by Django 6.0.1 on 2026-02-17 23:39

import apps.user.helpers
import django.db.models.deletion
import functools
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_address_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=128, verbose_name='verification code')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=functools.partial(apps.user.helpers.calcule_verification_code_expiration, minutes=7), verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_phone_constraint',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_1',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_2',
        ),
        migrations.AddField(
            model_name='address',
            name='apartament',
            field=models.CharField(blank=True, max_length=255, verbose_name='apartment number'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Indicates whether the user's email address has been verified.", verbose_name='is verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(models.F('phone'), condition=models.Q(('phone__isnull', False)), name='unique_phone_constraint'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'verification_code'], name='user_emailv_user_id_d4942e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='user_emailv_expires_c2d2e1_idx'),
        ),
    ]
