# Generated by Django 6.0.1 on 2026-02-26 21:58

import apps.user.helpers
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverification_alter_address_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=128, verbose_name='verification code')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=functools.partial(apps.user.helpers.calcule_verification_code_expiration, minutes=7), verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='user_emailv_user_id_d4942e_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='user_emailv_expires_c2d2e1_idx',
        ),
        migrations.AddField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['user', 'is_valid', '-created_at'], name='user_userve_user_id_3af108_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['expires_at'], name='user_userve_expires_0add98_idx'),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
