# Generated by Django 6.0.1 on 2026-03-06 20:51

import apps.authentication.helpers
import django.db.models.deletion
import functools
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=128, verbose_name='verification code')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='verification token')),
                ('purpose', models.CharField(choices=[('ACCOUNT_VERIFICATION', 'Account Verification'), ('MFA_AUTHENTICATION', 'Multi-factor Authentication'), ('EMAIL_CHANGE', 'Email Change'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset')], max_length=50)),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=functools.partial(apps.authentication.helpers.calcule_verification_code_expiration, minutes=7), verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_valid', '-created_at'], name='authenticat_user_id_44448c_idx'), models.Index(fields=['verification_token', 'purpose'], name='authenticat_verific_14d8d6_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_25786f_idx')],
            },
        ),
    ]
