# Generated by Django 6.0.1 on 2026-03-03 15:43

import apps.authentication.helpers
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=128, verbose_name='verification code')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=functools.partial(apps.authentication.helpers.calcule_verification_code_expiration, minutes=7), verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
