# Generated by Django 6.0.1 on 2026-03-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'is_valid', '-created_at'], name='authenticat_user_id_95e962_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_25786f_idx'),
        ),
    ]
